---
name: Continuous Integration

on:
  workflow_call:
    inputs:
      target:
        description: "Target"
        required: true
        type: string
      configuration:
        description: "Configuration"
        required: true
        type: string

permissions: {}

jobs:
  build:
    name: Build
    runs-on: [ubuntu-latest]
    container: ghcr.io/philips-software/amp-devcontainer-cpp:v6.0.2@sha256:36afaaa5ba4bc4e9bb471012db9733c26a210e315ddb33600f73bb9532b02a25 # 6.0.2
    steps:
      - uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
        with:
          disable-sudo-and-containers: true
          egress-policy: audit
      - uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
        if: ${{ inputs.target == 'windows' }}
        id: cache-winsdk
        with:
          path: /winsdk
          key: cache-winsdk
      - if: ${{ inputs.target == 'windows' && steps.cache-winsdk.outputs.cache-hit != 'true' }}
        run: xwin --accept-license --sdk-version "10.0.26100" --crt-version "14.43.17.13" splat --preserve-ms-arch-notation --include-debug-libs && mv .xwin-cache/splat/ /winsdk
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
          submodules: true
      - uses: hendrikmuhs/ccache-action@5ebbd400eff9e74630f759d94ddd7b6c26299639 # v1.2.20
        with:
          key: ${{ inputs.target}}-${{ inputs.configuration }}
      - uses: lukka/run-cmake@af1be47fd7c933593f687731bc6fdbee024d3ff4 # v10.8
        with:
          configurePreset: "${{ inputs.target }}"
          buildPreset: "${{ inputs.target }}-${{ inputs.configuration }}"
          configurePresetAdditionalArgs: "['-DCMAKE_C_COMPILER_LAUNCHER=ccache', '-DCMAKE_CXX_COMPILER_LAUNCHER=ccache']"
      - if: ${{ inputs.target == 'windows' }}
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: WindowsDiscovery
          path: ${{ github.workspace }}/build/**/*.exe
          retention-days: 8
      - if: ${{ inputs.target == 'stm32f407' && inputs.configuration == 'RelWithDebInfo' }}
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: postmaster
          path: build/stm32f407/Postmaster-*-Generic-ELF.tar.gz
          if-no-files-found: error
